name: Build Artifacts
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"

jobs:
  build_artifacts:
    name: Build Artifcats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Install vsce
        run: npm i -g @vscode/vsce
      - name: Install packages
        run: npm install
      - name: Build
        run: npm run build
      - name: Create Extension Package
        run: vsce package
      - name: Get Package Version
        id: get_version
        run: echo "VERSION=$(cat package.json | jq -r .version)" >> $GITHUB_ENV
      - name: Upload Artifcats
        uses: actions/upload-artifact@v3
        with:
          name: goatfile-${{ env.VERSION }}.vsix
          path: ./goatfile-${{ env.VERSION }}.vsix
          retention-day: 15
